### ISSUE TITLE
Comment:Step-Generators-Hook

### ISSUE THREAD

**Issue by orverduzco** [feathersjs/feathers-guide#7]
`feathers generate hook` is throwing an error with the following steps (running on the online documentation example: https://docs.feathersjs.com/guides/step-by-step/generators/gen-hook.html):
1. run `feathers generate hook`.
2. type `populateTeams` as the hook's name.
3. type `after` as the hook's kind.
4. type `find` as the hook's method.

This throws the following error:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: No hook declaration object for 'after' hooks found.
    at Collection.insertHook (/Users/omarverduzco/.nvm/versions/node/v6.9.1/lib/node_modules/feathers-cli/node_modules/generator-feathers/lib/transform.js:35:13)
    at methods.forEach.method (/Users/omarverduzco/.nvm/versions/node/v6.9.1/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/hook/index.js:32:11)
    at Array.forEach (native)
    at HookGenerator._transformHookFile (/Users/omarverduzco/.nvm/versions/node/v6.9.1/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/hook/index.js:31:13)
    at HookGenerator._addToService (/Users/omarverduzco/.nvm/versions/node/v6.9.1/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/hook/index.js:51:30)
    at props.services.forEach.serviceName (/Users/omarverduzco/.nvm/versions/node/v6.9.1/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/hook/index.js:144:14)
    at Array.forEach (native)
    at HookGenerator.writing (/Users/omarverduzco/.nvm/versions/node/v6.9.1/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/hook/index.js:143:27)
    at Object.<anonymous> (/Users/omarverduzco/.nvm/versions/node/v6.9.1/lib/node_modules/feathers-cli/node_modules/yeoman-generator/lib/index.js:417:23)
    at /Users/omarverduzco/.nvm/versions/node/v6.9.1/lib/node_modules/feathers-cli/node_modules/run-async/index.js:25:25
```

**Comment by eddyystop** [comment]
I notice you have not included the service name prompt in your example. That is part of the docs: https://docs.feathersjs.com/guides/step-by-step/generators/gen-hook.html#add-the-populate-hook

Did you run `feathers generate service` beforehand to create the `teams` service?

**Comment by daffl** [comment]
This should be fixed in the latest `feathers-cli`
